# Use root/mysql as user/password credentials

version: '3.8'

services:
  macmail_web_app:
    # image: iberlot/macmailling
    build:
      context: ./
      dockerfile: Dockerfile
    image: prueba-web
    command: gunicorn macmail.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 9000:8000
    env_file:
      - ./.env.dev
    hostname: web

  macmail_db_host:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: macmail_db
      MYSQL_USER: macmail_user
      MYSQL_PASSWORD: macmail_pass
    volumes:
      - ./data/db:/var/lib/mysql

  macmail_adminer:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=macmail_db_host
    hostname: adminer

volumes:
  macmail_db_volume:
  macmail_pgadmin-data:
  macmail_repo_data:
