# Generated by Django 4.1.3 on 2024-07-02 02:58

from django.db import migrations, models

def setup_types(apps, schema_editor):

    auxiliar_type = apps.get_model("auxiliares", "Type")

    list_mappings = [
        {'id': 1, 'name': 'Retailer', 'code': 48},
        {'id': 2, 'name': 'Distributor / Wholesaler', 'code': 46},
        {'id': 3, 'name': 'Corporation / Private entity', 'code': 60},
        {'id': 4, 'name': 'Manufacturer', 'code': 50},
        {'id': 5, 'name': 'MQ Prospect', 'code': 54},
        {'id': 6, 'name': 'Partner', 'code': 3180},
        {'id': 7, 'name': 'Government / Public entity', 'code': 58},
        {'id': 8, 'name': 'Broker', 'code': 44},
        {'id': 9, 'name': 'MQ Client', 'code': 52},
        {'id': 10, 'name': 'Hospitality (Hotels)', 'code': 1546},
        {'id': 11, 'name': 'Hospitality (Cafes/Bakeries)', 'code': 1547},
        {'id': 12, 'name': 'Hospitality (Restaurants)', 'code': 1548},
        {'id': 13, 'name': 'C-Store', 'code': 5502},
        {'id': 14, 'name': 'None', 'code': 99},
        {'id': 15, 'name': 'Logistics 3PL', 'code': 56},
        {'id': 16, 'name': 'E-Commerce', 'code': 2184},
        {'id': 17, 'name': 'Airline', 'code': 80},
        {'id': 18, 'name': 'Pharmacy', 'code': 82},
        {'id': 19, 'name': 'Entertainment / Parks', 'code': 1590}
    ]

    for mapping in list_mappings:
        auxiliar_type.objects.update_or_create(
            id=mapping['id'],
            defaults={
                'name': mapping['name'],
                'description': mapping['name'],
                'code': mapping['code']
            }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('amount_cnt', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('base', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=32)),
                ('lid', models.CharField(max_length=5)),
                ('format_string', models.CharField(max_length=32)),
                ('dec_point', models.CharField(max_length=1)),
                ('thousands_sep', models.CharField(max_length=1)),
                ('decimals', models.IntegerField(blank=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(setup_types)
    ]
