# Generated by Django 4.1.3 on 2024-07-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0004_alter_type_code_alter_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.CharField(max_length=64),
        ),
    ]
