""" Constantes para el módulo de reportes. """

import os


INDICE_TRADUCCION = {
    'id': 'id',
    'estatus': 'status',
    'título_de_prospecto': 'lead_name',
    'saludo': 'salutation',
    'nombre': 'first_name',
    'segundo_nombre': 'middle_name',
    'apellido': 'last_name',
    'fecha_de_nacimiento': 'date_of_birth',
    'creado': 'created',
    'origen': 'source',
    'observadores': 'observadores',
    'teléfono_del_trabajo': 'work_phone',
    'móvil': 'mobile',
    'fax': 'fax',
    'teléfono_de_casa': 'home_phone',
    'número_del_localizador': 'pager_number',
    'teléfono_para_sms_marketing': 'sms_marketing_phone',
    'otro_número_de_teléfono': 'other_phone_number',
    'sitio_web_corporativo': 'corporate_website',
    'página_personal': 'personal_page',
    'página_del_facebook': 'facebook_page',
    'página_vk': 'vk_page',
    'livejournal': 'livejournal',
    'twitter': 'twitter',
    'otro_sitio_web': 'other_website',
    'e_mail_del_trabajo': 'work_e_mail',
    'e_mail_de_la_casa': 'home_e_mail',
    'correo_electrónico_para_boletines_informativos': 'newsletters_email',
    'otro_e_mail': 'other_e_mail',
    'cuenta_de_facebook': 'facebook_account',
    'cuenta_de_telegram': 'telegram_account',
    'cuenta_vk': 'vk_account',
    'id_del_skype': 'skype_id',
    'contacto_de_viber': 'viber_contact',
    'comentarios_de_instagram': 'instagram_comments',
    'cuenta_bitrix24network': 'bitrix24network_account',
    'chat_en_vivo': 'live_chat',
    'cuenta_de_canal_abierto': 'open_channel_account',
    'número_de_icq': 'icq_number',
    'msnlive!': 'msnlive!',
    'jabber': 'jabber',
    'otro_contacto': 'other_contact',
    'usuario_vinculado': 'linked_user',
    'responsable': 'responsible',
    'información_de_estado': 'status_information',
    'información_de_origen': 'source_information',
    'creado_por': 'created_by',
    'modificado': 'modified',
    'modificado_por': 'modified_by',
    'nombre_de_la_compañía': 'company_name',
    'cargo': 'position',
    'dirección': 'address',
    'calle_casa_núm': 'street_house_no',
    'departamento_oficina_habitación_piso': 'apartment_office_room_floor',
    'ciudad': 'city',
    'distrito': 'district',
    'regiónárea': 'regionarea',
    'código_postal': 'zippostal_code',
    'país': 'country',
    'comentario': 'comment',
    'total': 'total',
    'moneda': 'currency',
    'producto': 'product',
    'precio': 'price',
    'cantidad': 'quantity',
    'creado_por_el_formulario_del_crm': 'created_by_crm_form',
    'prospecto_repetido': 'repeat_lead',
    'cliente': 'client',
    'recorrido_del_cliente': 'customer_journey',
    'utm_source': 'utm_source',
    'utm_medium': 'utm_medium',
    'utm_campaign': 'utm_campaign',
    'utm_content': 'utm_content',
    'utm_term': 'utm_term',
    'type': 'type',
    'country': 'country',
    'account': 'account',
    'addl_type_details_other': 'addl_type_details_other',
    'gg_sheet_row': 'gg_sheet_row',
    'gg_sheet_id': 'gg_sheet_id',
    'sub_type_hmcdelos': 'industry_sub_type',
    'última_actualización_en': 'last_updated_on',
}


INDICE_TRADUCCION_CONTACT = {
    'Teléfono del trabajo': 'Work Phone',
    'Móvil': 'Mobile',
    'Fax': 'Fax',
    'Teléfono de casa': 'Home Phone',
    'Número del localizador': 'Pager Number',
    'Teléfono para SMS Marketing': 'SMS marketing phone',
    'Otro número de teléfono': 'Other Phone Number',
    'Sitio web Corporativo': 'Corporate Website',
    'Página personal': 'Personal Page',
    'Página del Facebook': 'Facebook Page',
    'Página VK': 'VK Page',
    'LiveJournal': 'LiveJournal',
    'Twitter': 'Twitter',
    'Otro sitio web': 'Other Website',
    'E-mail del trabajo': 'Work E-mail',
    'E-mail de la Casa': 'Home E-mail',
    'Correo electrónico para boletines informativos': 'Newsletters email',
    'Otro e-mail': 'Other E-mail',
    'Cuenta de Facebook': 'Facebook account',
    'Cuenta de Telegram': 'Telegram account',
    'Cuenta VK': 'VK account',
    'ID del Skype': 'Skype ID',
    'Contacto de Viber': 'Viber contact',
    'Comentarios de Instagram': 'Instagram comments',
    'Cuenta Bitrix24.Network': 'Bitrix24.Network account',
    'Chat en vivo': 'Live Chat',
    'Cuenta de Canal Abierto': 'Open Channel account',
    'Número de ICQ': 'ICQ Number',
    'MSN/Live!': 'MSN/Live!',
    'Jabber': 'Jabber',
    'Otro Contacto': 'Other Contact',
    'Usuario vinculado': 'Linked user',
}


API_BASE_URL = os.environ.get('API_BASE_URL')
BITRIX_BASE_URL = os.environ.get('BITRIX_BASE_URL')
BITRIX_WEBHOOK = os.environ.get("BITRIX_WEBHOOK", "v0uehhaf88vle9ua")
