# Generated by Django 4.1.3 on 2023-10-03 13:50

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auxiliares', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('lead_name', models.CharField(blank=True, max_length=64, null=True)),
                ('salutation', models.CharField(blank=True, choices=[('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Other', 'Other')], max_length=16, null=True)),                
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
                ('status_information', models.CharField(blank=True, max_length=32, null=True)),
                ('source_information', models.CharField(blank=True, max_length=256, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=64, null=True)),
                ('position', models.CharField(blank=True, max_length=64, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('currency', models.CharField(blank=True, choices=[('US Dollar', 'US Dollar')], max_length=16, null=True)),
                ('product', models.CharField(blank=True, max_length=32, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created_by_crm_form', models.CharField(blank=True, max_length=32, null=True)),
                ('repeat_lead', models.BooleanField(blank=True, default=False, null=True)),
                ('client', models.CharField(blank=True, max_length=32, null=True)),
                ('customer_journey', models.CharField(blank=True, max_length=32, null=True)),
                ('addl_type_details_other', models.CharField(blank=True, max_length=32, null=True)),
                ('industry_sub_type', models.CharField(blank=True, max_length=32, null=True)),
                ('last_updated_on', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.account')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.country')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'clientes',
                'ordering': ('cliente_id',),
            },
        ),
        migrations.CreateModel(
            name='ClientesAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('street_house_no', models.CharField(blank=True, max_length=32, null=True)),
                ('apartment_office_room_floor', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('district', models.CharField(blank=True, max_length=32, null=True)),
                ('region_area', models.CharField(blank=True, max_length=32, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=32, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.country')),
            ],
        ),
        migrations.CreateModel(
            name='ClientesContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=64, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.contacttype')),
            ],
        ),
         migrations.CreateModel(
            name='ClientesEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=64, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.emailtype')),
            ],
        ),
        migrations.CreateModel(
            name='ClientesSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=64, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.socialtype')),
            ],
        ),
        migrations.CreateModel(
            name='ClientesUTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Codigo', max_length=64)),
                ('medium', models.CharField(help_text='Medio', max_length=64)),
                ('campaign', models.CharField(help_text='Campaign', max_length=64)),
                ('content', models.CharField(help_text='Content', max_length=64)),
                ('term', models.CharField(help_text='Term', max_length=64)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='ClientesWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=64, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.webtype')),
            ],
        ),
         migrations.CreateModel(
            name='ExcelFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='excel_files/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=64, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('status_response', models.BooleanField(default=False)),
                ('use_template', models.BooleanField(default=False)),
                ('send_number', models.IntegerField(default=0)),
                ('last_send', models.DateTimeField(blank=True, null=True)),
                ('reminder_days', models.IntegerField(default=7)),
                ('attachment', models.ManyToManyField(blank=True, to='reportes.attachment')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='MailCorp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('smtp', models.CharField(blank=True, max_length=64, null=True)),
                ('smtp_port', models.CharField(blank=True, max_length=64, null=True)),
                ('imap', models.CharField(blank=True, max_length=64, null=True)),
                ('imap_port', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('firma', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailsToSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('send', models.BooleanField(default=False)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.mail')),
                ('user_approved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sudject', max_length=64)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(blank=True, null=True, upload_to='template_files/')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplatesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('mail_corp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.mailcorp')),
            ],
        ),
        migrations.CreateModel(
            name='UserAcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_usr_acount', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='templatefiles',
            name='template_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.templatesgroup'),
        ),
        migrations.AddField(
            model_name='mail',
            name='mail_corp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.mailcorp'),
        ),
        migrations.AddField(
            model_name='mail',
            name='template_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.templatesgroup'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='creado_por', to='reportes.mailcorp'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='modificado_por', to='reportes.mailcorp'),       
        ),
        migrations.AddField(
            model_name='clientes',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='responsable', to='reportes.mailcorp'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.type'),
        ),
    ]

