# Generated by Django 4.1.3 on 2024-01-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='contacted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='contacted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='source_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientesaddress',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientesaddress',
            name='street_house_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientesemail',
            name='data',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clientessocial',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientesweb',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mail',
            unique_together={('cliente', 'mail_corp')},
        ),
    ]
