# Generated by Django 4.1.3 on 2024-02-29 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0002_initial'),
        ('reportes', '0005_alter_clientescontact_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.type'),
        ),
    ]
