# Generated by Django 4.1.3 on 2024-03-27 11:20

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_alter_clientes_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ('cliente_id',), 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='clientesaddress',
            options={'verbose_name': 'customer address', 'verbose_name_plural': 'customer address'},
        ),
        migrations.AlterModelOptions(
            name='clientescontact',
            options={'verbose_name': 'customer contact', 'verbose_name_plural': 'customer contacts'},
        ),
        migrations.AlterModelOptions(
            name='clientesemail',
            options={'verbose_name': 'customer email', 'verbose_name_plural': 'customer emails'},
        ),
        migrations.AlterModelOptions(
            name='clientessocial',
            options={'verbose_name': 'customer social', 'verbose_name_plural': 'customer socials'},
        ),
        migrations.AlterModelOptions(
            name='clientesutm',
            options={'verbose_name': 'customer utm', 'verbose_name_plural': 'customer utms'},
        ),
        migrations.AlterModelOptions(
            name='clientesweb',
            options={'verbose_name': 'customer web', 'verbose_name_plural': 'customer webs'},
        ),
        migrations.AlterModelOptions(
            name='excelfiles',
            options={'verbose_name': 'excel file', 'verbose_name_plural': 'excel files'},
        ),
        migrations.AlterModelOptions(
            name='templatefiles',
            options={'verbose_name': 'template file', 'verbose_name_plural': 'template files'},
        ),
        migrations.AlterField(
            model_name='clientesaddress',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='clientescontact',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='clientesemail',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='clientessocial',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='clientesutm',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='clientesweb',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='mailcorp',
            name='firma',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='signature'),
        ),
        migrations.AlterField(
            model_name='templatefiles',
            name='name',
            field=models.CharField(default='Sudject', max_length=64, verbose_name='Subject'),
        ),
    ]
