# Generated by Django 4.1.3 on 2024-03-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_alter_clientes_options_alter_clientesaddress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailstosend',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailstosend',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
