# Generated by Django 4.1.3 on 2024-07-02 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0011_templatesgroup_max_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ('cliente_id',), 'verbose_name': 'lead', 'verbose_name_plural': 'leads'},
        ),
        migrations.AlterModelOptions(
            name='clientesaddress',
            options={'verbose_name': 'lead address', 'verbose_name_plural': 'lead address'},
        ),
        migrations.AlterModelOptions(
            name='clientescontact',
            options={'verbose_name': 'lead contact', 'verbose_name_plural': 'lead contacts'},
        ),
        migrations.AlterModelOptions(
            name='clientesemail',
            options={'verbose_name': 'lead email', 'verbose_name_plural': 'lead emails'},
        ),
        migrations.AlterModelOptions(
            name='clientessocial',
            options={'verbose_name': 'lead social', 'verbose_name_plural': 'lead socials'},
        ),
        migrations.AlterModelOptions(
            name='clientesutm',
            options={'verbose_name': 'lead utm', 'verbose_name_plural': 'lead utms'},
        ),
        migrations.AlterModelOptions(
            name='clientesweb',
            options={'verbose_name': 'lead web', 'verbose_name_plural': 'lead webs'},
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cliente_id',
            field=models.IntegerField(unique=True, verbose_name='lead id'),
        ),
        migrations.AlterField(
            model_name='clientesaddress',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='lead'),
        ),
        migrations.AlterField(
            model_name='clientescontact',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='lead'),
        ),
        migrations.AlterField(
            model_name='clientesemail',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='lead'),
        ),
        migrations.AlterField(
            model_name='clientessocial',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='lead'),
        ),
        migrations.AlterField(
            model_name='clientesutm',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='lead'),
        ),
        migrations.AlterField(
            model_name='clientesweb',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='lead'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='lead'),
        ),
    ]
