# Generated by Django 4.1.3 on 2024-07-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0012_alter_clientes_options_alter_clientesaddress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
