# Generated by Django 4.1.3 on 2024-07-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0013_clientes_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='attachment',
        ),
        migrations.AddField(
            model_name='templatefiles',
            name='attachment',
            field=models.ManyToManyField(blank=True, to='reportes.attachment'),
        ),
    ]
