# Generated by Django 4.1.3 on 2024-07-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0014_remove_mail_attachment_templatefiles_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefiles',
            name='name',
            field=models.CharField(default='Subject', max_length=64, verbose_name='Subject'),
        ),
        migrations.AddConstraint(
            model_name='mailstosend',
            constraint=models.UniqueConstraint(condition=models.Q(('send', False)), fields=('mail',), name='unique_mail_send_false'),
        ),
    ]
