# Generated by Django 4.1.3 on 2024-07-05 02:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0016_alter_attachment_created_alter_attachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='mail',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes', verbose_name='lead'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.mailcorp'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='mail',
            name='template_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.templatesgroup'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='use_template',
            field=models.BooleanField(default=True),
        ),
    ]
