# Generated by Django 4.1.3 on 2024-07-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0017_alter_mail_body_alter_mail_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailstosend',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mailstosend',
            unique_together={('mail', 'order')},
        ),
    ]
