# Generated by Django 4.1.3 on 2024-07-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0019_alter_clientes_first_name_alter_clientes_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
