# Generated by Django 4.1.3 on 2024-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0020_alter_mail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcorp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
