# Generated by Django 4.1.3 on 2024-08-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0021_alter_mailcorp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesemail',
            name='data',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='mail',
            unique_together={('cliente', 'mail_corp', 'template_group')},
        ),
        migrations.AddConstraint(
            model_name='mail',
            constraint=models.UniqueConstraint(condition=models.Q(('status', True)), fields=('cliente',), name='unique_mail_status_true'),
        ),
    ]
