# Generated by Django 4.1.3 on 2024-02-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_clientes_contacted_clientes_contacted_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cliente_id',
            field=models.IntegerField(unique=True),
        ),
    ]
