# Generated by Django 4.1.3 on 2024-02-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_clientes_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='position',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
