# Generated by Django 4.1.3 on 2024-02-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0002_initial'),
        ('reportes', '0004_alter_clientes_position_alter_mail_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientescontact',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes'),
        ),
        migrations.AlterField(
            model_name='clientescontact',
            name='data',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='clientescontact',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.contacttype'),
        ),
        migrations.AlterField(
            model_name='clientesemail',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes'),
        ),
        migrations.AlterField(
            model_name='clientesemail',
            name='data',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='clientesemail',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.emailtype'),
        ),
        migrations.AlterField(
            model_name='clientessocial',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes'),
        ),
        migrations.AlterField(
            model_name='clientessocial',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clientessocial',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.socialtype'),
        ),
        migrations.AlterField(
            model_name='clientesweb',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes'),
        ),
        migrations.AlterField(
            model_name='clientesweb',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clientesweb',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.webtype'),
        ),
        migrations.AlterUniqueTogether(
            name='clientescontact',
            unique_together={('cliente', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='clientesemail',
            unique_together={('cliente', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='clientessocial',
            unique_together={('cliente', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='clientesweb',
            unique_together={('cliente', 'type')},
        ),
    ]
