# Generated by Django 4.1.3 on 2023-03-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_alter_registroslibros_riesgo_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('lead_name', models.CharField(blank=True, max_length=64, null=True)),
                ('salutation', models.CharField(blank=True, choices=[('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Other', 'Other')], max_length=16, null=True)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='registroslibros',
            name='libro',
        ),
        migrations.DeleteModel(
            name='LibrosRubricados',
        ),
        migrations.DeleteModel(
            name='RegistrosLibros',
        ),
    ]
