# Generated by Django 4.1.3 on 2023-03-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0006_clientes_remove_registroslibros_libro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countrys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ('cliente_id',), 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AddField(
            model_name='clientes',
            name='account',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='addl_type_details_other',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='client',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='company_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientes',
            name='created_by_crm_form',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='currency',
            field=models.CharField(blank=True, choices=[('US Dollar', 'US Dollar')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='customer_journey',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='industry_sub_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='last_updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientes',
            name='position',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='product',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='repeat_lead',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientes',
            name='source_information',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='status_information',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterModelTable(
            name='clientes',
            table='clientes',
        ),
        migrations.CreateModel(
            name='ClientesWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=64, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.webtype')),
            ],
        ),
        migrations.CreateModel(
            name='ClientesUTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Codigo', max_length=64)),
                ('medium', models.CharField(help_text='Medio', max_length=64)),
                ('campaign', models.CharField(help_text='Campaign', max_length=64)),
                ('content', models.CharField(help_text='Content', max_length=64)),
                ('term', models.CharField(help_text='Term', max_length=64)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='ClientesSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=64, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.socialtype')),
            ],
        ),
        migrations.CreateModel(
            name='ClientesEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=64, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.emailtype')),
            ],
        ),
        migrations.CreateModel(
            name='ClientesContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=64, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.contacttype')),
            ],
        ),
        migrations.CreateModel(
            name='ClientesAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('street_house_no', models.CharField(blank=True, max_length=32, null=True)),
                ('apartment_office_room_floor', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('district', models.CharField(blank=True, max_length=32, null=True)),
                ('region_area', models.CharField(blank=True, max_length=32, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=32, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.countrys')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.countrys'),
        ),
    ]
