# Generated by Django 4.1.3 on 2024-05-07 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_alter_clientes_options_alter_clientesaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailstosend',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reportes.mail'),
        ),
    ]
