# Generated by Django 4.1.3 on 2023-04-04 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0007_contacttype_countrys_emailtype_socialtype_webtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailCorp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('smtp', models.CharField(blank=True, max_length=64, null=True)),
                ('smtp_port', models.CharField(blank=True, max_length=64, null=True)),
                ('imap', models.CharField(blank=True, max_length=64, null=True)),
                ('imap_port', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=64, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('send_number', models.IntegerField(default=0)),
                ('last_send', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.ManyToManyField(blank=True, to='reportes.attachment')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.clientes')),
                ('mail_corp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.mailcorp')),
            ],
        ),
    ]
