# Generated by Django 4.1.3 on 2024-05-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_mailstosend_error_message_mailstosend_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesgroup',
            name='max_number',
            field=models.IntegerField(default=1),
        ),
    ]
