# Generated by Django 4.1.3 on 2023-04-08 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_excelfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 8, 19, 36, 30, 407911, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
