# Generated by Django 4.1.3 on 2023-04-13 14:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0010_alter_excelfiles_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='creado_por', to='reportes.mailcorp'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='modificado_por', to='reportes.mailcorp'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='responsable', to='reportes.mailcorp'),
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 13, 14, 23, 9, 206040, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='UserAcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_usr_acount', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
