# Generated by Django 4.1.3 on 2023-04-16 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0011_alter_clientes_created_by_alter_clientes_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesaddress',
            name='apartment_office_room_floor',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 16, 3, 24, 38, 482231, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
