# Generated by Django 4.1.3 on 2023-05-05 13:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0012_alter_clientesaddress_apartment_office_room_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='status_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='use_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 5, 13, 19, 55, 347970, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='TemplatesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 5, 13, 19, 55, 346342, tzinfo=datetime.timezone.utc), null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='excel_files/')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 5, 13, 19, 55, 346601, tzinfo=datetime.timezone.utc), null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('template_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.templatesgroup')),
            ],
        ),
        migrations.AddField(
            model_name='mail',
            name='template_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.templatesgroup'),
        ),
    ]
