# Generated by Django 4.1.3 on 2023-05-22 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0013_mail_status_response_mail_use_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='source_information',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 22, 18, 10, 14, 732775, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='templatefiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 22, 18, 10, 14, 731340, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='templatefiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='template_files/'),
        ),
        migrations.AlterField(
            model_name='templatesgroup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 22, 18, 10, 14, 731055, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
