# Generated by Django 4.1.3 on 2023-05-23 11:19

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0014_alter_clientes_source_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 11, 19, 11, 302319, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templatefiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 11, 19, 11, 300867, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='templatesgroup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 11, 19, 11, 300532, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
