# Generated by Django 4.1.3 on 2023-05-23 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0015_alter_excelfiles_created_alter_mail_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='reminder_days',
            field=models.ImageField(default=7, upload_to=''),
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 14, 51, 36, 393208, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='templatefiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 14, 51, 36, 391699, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='templatesgroup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 14, 51, 36, 391373, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
