# Generated by Django 4.1.3 on 2023-05-25 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0016_mail_reminder_days_alter_excelfiles_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 25, 14, 4, 4, 375417, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='reminder_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='templatefiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 25, 14, 4, 4, 373957, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='templatesgroup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 25, 14, 4, 4, 373661, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
