# Generated by Django 4.1.3 on 2023-06-01 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0017_alter_excelfiles_created_alter_mail_reminder_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 1, 15, 51, 50, 460383, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='mailcorp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='templatefiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 1, 15, 51, 50, 458972, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='templatesgroup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 1, 15, 51, 50, 458674, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
