# Generated by Django 4.1.3 on 2023-06-16 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0019_alter_excelfiles_created_alter_templatefiles_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefiles',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 16, 10, 54, 17, 663914, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='templatefiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 16, 10, 54, 17, 662139, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='templatesgroup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 16, 10, 54, 17, 661775, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
