# Generated by Django 4.1.3 on 2023-06-16 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0020_templatefiles_text_alter_excelfiles_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 16, 11, 6, 38, 328939, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='mailcorp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='templatefiles',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 16, 11, 6, 38, 327211, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='templatesgroup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 16, 11, 6, 38, 326877, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
