# Generated by Django 4.1.3 on 2023-06-16 17:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0023_alter_attachment_created_alter_excelfiles_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesgroup',
            name='mail_corp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.mailcorp'),
        ),
        migrations.AlterField(
            model_name='templatefiles',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
