# Generated by Django 4.1.3 on 2023-07-19 14:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0024_templatesgroup_mail_corp_alter_templatefiles_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcorp',
            name='firma',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
