name: 'coverage'
on:
    pull_request:
        branches:
            - main
            - develop
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout action
              uses: actions/checkout@v2
            - name: Django Coverage action
              uses: dc740/django-coveragepy-github-action@0.9
              with:
                django-app: 'reportes'
                minimum-coverage: '86'
          
